#[
autogenerated by docgen
loc: /home/runner/work/Nim/Nim/lib/js/jsre.nim(72, 3)
rdoccmd: 
]#
import "/home/runner/work/Nim/Nim/lib/js/jsre.nim"
let jsregex: RegExp = newRegExp(r"bcd", r"i")
assert "abcd".endsWith jsregex
