#[
autogenerated by docgen
loc: /home/runner/work/Nim/Nim/lib/js/jsre.nim(65, 3)
rdoccmd: 
]#
import "/home/runner/work/Nim/Nim/lib/js/jsre.nim"
let jsregex: RegExp = newRegExp(r"abc", r"i")
assert "abcd".startsWith jsregex
